### ISSUE TITLE
Remove my name from readme.txt

### ISSUE THREAD

**Issue by jovrtn** [bahstrike/ACAudio#1]
Can you please remove "Maethor" from the Advice and Discussion section of readme.txt? I don't endorse this project as you blatantly stole the initial idea after I mentioned it during an unrelated discussion. Thanks.

**Comment by bahstrike** [comment]
Here are the commit references that remove your name:
Readme's: 75e163113956c7628cf62a4fe0cc3867ea9fbf04
Website: 539954f2bcc58f36973dff53f685ba8763bc530b
